### ISSUE TITLE
[request] 1.19.2

### ISSUE THREAD

**Issue by Hate9** [walksanatora/hexxy-dimensions#1]
Hey, look, I know nobody ever wants to do backports, and I seriously get it, but *most* hexcasting mods aren't available for 1.20 yet, so I'd really, *really* appreciate it if you backported this to 1.19.2.
I'm sure they'll all eventually start to support 1.20, but until then, there's no way to play with all the others.
If you *do* backport this, then someone can play with hexal and moreiotas and hexbound and hextweaks and hexkinetics and hex gloop and mediaworks and hexlink and even gravity api and pehkui.

**Comment by walksanatora** [comment]
i will look into a 1.19.2 backport
the only things that may be a bit *iffy* (hard to implement) is the custom iotas (since they don't exist in 1.19.2)
but I can substitute them for a [num,num] list

**Comment by Hate9** [comment]
Thanks so much! And oh cool! They aren't up on modrinth yet, but cool to know that a bunch are already updated to 1.20!

**Comment by walksanatora** [comment]
done it is now up on modrinth
